# Generated by Django 2.2.14 on 2020-07-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_event_publication_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventState',
            fields=[
                ('state', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
