# Generated by Django 2.2.14 on 2020-07-09 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_eventstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='state',
            field=models.ForeignKey(default='public', on_delete=django.db.models.deletion.CASCADE, to='website.EventState'),
        ),
    ]
