# Generated by Django 2.2.14 on 2020-07-13 07:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0004_event_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='subscription',
            field=models.ManyToManyField(related_name='event_subscription', to=settings.AUTH_USER_MODEL),
        ),
    ]
