# Generated by Django 2.2.14 on 2020-07-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20200713_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='exerpt',
            field=models.CharField(default='This is the default exerpt for a post', max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
