# Generated by Django 2.2.14 on 2020-07-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20200713_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='exerpt',
            field=models.CharField(max_length=255),
        ),
    ]
