# Generated by Django 2.2.14 on 2020-07-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20200713_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/default_image.png', null=True, upload_to='images/profile/'),
        ),
    ]
