# Generated by Django 2.2.14 on 2020-07-15 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20200714_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='subscription',
        ),
    ]
