# Generated by Django 2.2.14 on 2020-07-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_remove_event_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='images/profile/default_profile.png', upload_to='images/profile/'),
        ),
    ]
